[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "ae32fedff2a7f0ea81eac9860c9f45bf316e4ba7"
lazy = true
libc = "glibc"
os = "linux"

    [[libopenjph_c.download]]
    sha256 = "47c521201a0c3e25e163f090ab15d71084afc6acbc640ec82b53a66d5b9fd2fe"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/native-snapshot-three-way-release-scheme/openjph_c-linux-x86_64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "a71e40ccf381883008b465db54c3b17a8d2a5858"
lazy = true
libc = "glibc"
os = "linux"

    [[libopenjph_c.download]]
    sha256 = "e8f3c44becfed7d4aac985eeb5f99b9b6a7f59dba6fe0574c6bfc557a77af903"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/native-snapshot-three-way-release-scheme/openjph_c-linux-aarch64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "489eb81073756c71c98ab87f468daead218ba7d6"
lazy = true
os = "macos"

    [[libopenjph_c.download]]
    sha256 = "682445534529e759bc47ec0022e5f9e69cf0ee4b264d4c0d5eed5f91fc622817"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/native-snapshot-three-way-release-scheme/openjph_c-macos-aarch64.tar.gz"
[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "33d88f01b10c47566b46d19bb846edfb99496d98"
lazy = true
os = "macos"

    [[libopenjph_c.download]]
    sha256 = "cc93708a49e4a9713b525fcf9f3cf59dd8dcfc1624483f530769aab5db690d46"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/native-snapshot-three-way-release-scheme/openjph_c-macos-x86_64.tar.gz"
[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "f1c4c886f4c444ce87744882062550825e51b487"
lazy = true
os = "windows"

    [[libopenjph_c.download]]
    sha256 = "c659cb8c9578a351522862aa6135a40bee2833ce1ed4501b7846accf35468292"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/native-snapshot-three-way-release-scheme/openjph_c-windows-x86_64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "981b724ae4816427b2f6cd920eb8921f405e55ae"
lazy = true
os = "windows"

    [[libopenjph_c.download]]
    sha256 = "38b716a85698b50484316a2629cd61f8b91fe23ef26f8b47703082f175d3522a"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/native-snapshot-three-way-release-scheme/openjph_c-windows-aarch64.tar.gz"
