[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "68df00deb0b9b555ac05b07c70936cb317fecf98"
lazy = true
libc = "glibc"
os = "linux"

    [[libopenjph_c.download]]
    sha256 = "6bccf8688925a4f4751de6255e164f6234b579759fc88fd7dd524ae0f2c1fe4d"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.1/openjph_c-linux-x86_64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "30f44d77be0fcf53145bacc766d2c35f0b068ab4"
lazy = true
libc = "glibc"
os = "linux"

    [[libopenjph_c.download]]
    sha256 = "d858aadc5c05b508c83b7c1bd247dea54814c9bbdb2d4352b0c4547242f36715"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.1/openjph_c-linux-aarch64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "dab970ea0645f49ba01d0c5d7d2630b7035bad56"
lazy = true
os = "macos"

    [[libopenjph_c.download]]
    sha256 = "15939cb213773deeaf5b4383434b4ac241ebfd3bc36f0fd3c35ee84e4b4755e4"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.1/openjph_c-macos-aarch64.tar.gz"
[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "c7ffc7a038963b3ff2c38d888388003e2c04ffe2"
lazy = true
os = "macos"

    [[libopenjph_c.download]]
    sha256 = "10917d7ce2077136b83ec462088b35cbd6cb2dc759c99716eb94ca325405411d"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.1/openjph_c-macos-x86_64.tar.gz"
[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "d221d1317558393ff36c0c3e7987ed156c2f018b"
lazy = true
os = "windows"

    [[libopenjph_c.download]]
    sha256 = "423f50769a4c3c128cbb1a3ff1929509ce52d9bf9f8fed2297737c2701f8f487"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.1/openjph_c-windows-x86_64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "a9b550b38e6bcf022596dee99d32fe7ddece62de"
lazy = true
os = "windows"

    [[libopenjph_c.download]]
    sha256 = "823d9e9383ee44e195771582549998e86df1fef0317c54061ce2f164c552432e"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.1/openjph_c-windows-aarch64.tar.gz"
