[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "0f0fecf15bf0e13d6ace0fc98b80ba67aba1e26e"
lazy = true
libc = "glibc"
os = "linux"

    [[libopenjph_c.download]]
    sha256 = "3e47a299aa5629da33152cc8244c17db41ef060766baced6bc5fb166a773c8e4"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.4/openjph_c-linux-x86_64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "2abdd7b5dbfe9f8b7f9c3c57336c8ebd66f72a76"
lazy = true
libc = "glibc"
os = "linux"

    [[libopenjph_c.download]]
    sha256 = "4eabe4dd8e827942e894bc903b6fa2a038e4dadabeb814afceb98249c1f849d8"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.4/openjph_c-linux-aarch64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "870dd02c9af296025800650d81802983eddf953c"
lazy = true
os = "macos"

    [[libopenjph_c.download]]
    sha256 = "4bd37daae20a39ff296268adfe617d099e6d75fd812cf8324d69270b931ecf5b"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.4/openjph_c-macos-aarch64.tar.gz"
[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "4a93fcc73766adb7e5ad2449f9a2fb18c78d9dbe"
lazy = true
os = "macos"

    [[libopenjph_c.download]]
    sha256 = "718d659f06778c6ae47d9dee8b25b1c2b3dda4be8e999ed5c0f6fa7b61781e61"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.4/openjph_c-macos-x86_64.tar.gz"
[[libopenjph_c]]
arch = "x86_64"
git-tree-sha1 = "129abd7e647fbdb2856be5c66e7ee126b59515ef"
lazy = true
os = "windows"

    [[libopenjph_c.download]]
    sha256 = "b95002ae9b7bc735febe57302775d37e7551b4dc7320fd6a5d2efdd74cc1f64b"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.4/openjph_c-windows-x86_64.tar.gz"
[[libopenjph_c]]
arch = "aarch64"
git-tree-sha1 = "20ed970672c9916ded96b7e7218a3a762a52f2f0"
lazy = true
os = "windows"

    [[libopenjph_c.download]]
    sha256 = "d91fabc8b4bb5e5b23922afd75dd1768abee7965c54ff4508eb29adf60ec1d11"
    url = "https://github.com/Clepio-Biotech/openjph-bindings/releases/download/C-v0.29.0.4/openjph_c-windows-aarch64.tar.gz"
