name: tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install cmake
        run: sudo apt-get install -y cmake
      - name: Install
        env:
          NATIVE_PATH: ${{ github.workspace }}/native
        run: python -m pip install -e "./python[dev]"
      - name: Run pre-commit
        run: pre-commit run --all-files

  python-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install cmake
        run: sudo apt-get install -y cmake
      - name: Install
        env:
          NATIVE_PATH: ${{ github.workspace }}/native
        run: python -m pip install ".[test,zarr]"
      - name: Test
        run: pytest tests

  julia-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: Install cmake
        run: sudo apt-get install -y cmake
      - name: Build OpenJPH
        env:
          NATIVE_PATH: ${{ github.workspace }}/native
        run: julia --project=julia/OpenJPH.jl -e 'import Pkg; Pkg.build("OpenJPH")'
      - name: Test OpenJPH
        run: julia --project=julia/OpenJPH.jl -e 'import Pkg; Pkg.test("OpenJPH")'
      - name: Test ZarrCompressorJPH
        run: julia --project=julia/ZarrCompressorJPH.jl -e 'import Pkg; Pkg.test("ZarrCompressorJPH")'
